volumes:
  postgres_data:
  mailpit_data:
  app_logs:
  redis_data:
  rabbitmq_data:
  flower_data:


networks:
  nextgen-local-network:
    external: true
    driver: bridge

services:
  traefik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    container_name: traefik
    command:
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/local/traefik/conf/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - nextgen-local-network

  api: &api
    build:
      context: .
      dockerfile: ./docker/local/fastapi/Dockerfile
    container_name: api
    volumes:
      - ./src/app/:/src/app/:delegated
      - app_logs:/src/app/logs:delegated
    command: /start.sh
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    env_file:
      - ./envs/.env.local
    networks:
      - nextgen-local-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  mailpit:
    image: docker.io/axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    container_name: mailpit
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - nextgen-local-network

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    container_name: db
    env_file:
      - ./envs/.env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextgen-local-network

  redis:
    image: docker.io/redis:7.0-alpine
    command: redis-server --appendonly yes
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nextgen-local-network

  rabbitmq:
    image: docker.io/rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nextgen-local-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      # - "traefik.http.routers.rabbitmq.service=rabbitmq-service"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  celery_worker:
    <<: *api
    container_name: celery_worker
    ports: []
    command: /worker_start.sh

  flower:
    <<: *api
    container_name: flower
    ports:
      - "5555:5555"
    command: /flower_start.sh
    volumes:
      - flower_data:/data
    depends_on:
      - rabbitmq
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
      # - "traefik.http.routers.flower.service=flower-service"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"

  celery_beat:
    <<: *api
    container_name: celery_beat
    ports: []
    command: /beat_start.sh
    depends_on:
      - rabbitmq
      - redis
